matrix:
  include:
    - language: go
      name: test make process
      go:
        - 1.13.x
      sudo: false
      cache:
        directories:
          - /home/travis/.cache/go-build
          - /home/travis/gopath/pkg/mod
      env:
        - GOPROXY=https://proxy.golang.org/
      script:
        - make check

    - language: ruby
      rvm: 2.6
      name: Site gem vulnerability check
      sudo: false # route your build to the container-based infrastructure for a faster build
      cache: bundler
      before_script:
        - chmod +x ./ciscripts/site-gem-vulnerability-test/cibuild
      script:
        - ./ciscripts/site-gem-vulnerability-test/cibuild

    - language: ruby
      rvm: 2.6
      name: Site Proofing
      sudo: false # route your build to the container-based infrastructure for a faster build
      cache: bundler
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
      before_install:
        - gem install bundler
        - gem install htmlproofer
        - gem install jekyll -v 3.8.5
      before_script:
        - chmod +x ./ciscripts/site-proofing/cibuild
      script:
        - ./ciscripts/site-proofing/cibuild